# Site details
name: Absent-minded architecture
description: Lessons learned in integration
meta_description: "Architecture and integration blog"
author:             'Mike Gough'
author_description: 'Integration Architect'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
domain_name: 'https://mike-gough.github.io'
google_analytics: 'UA-141675879-1'
gems: [jekyll-paginate]

# Navigation
base_url: '/'
permalink: /blog/posts/:year/:month/:day/:title:output_ext

# Details for the RSS feed generator
url:                'https://mike-gough.github.io/'