name: Absent-minded architecture
description: Lessons learned in integration
meta_description: "Architecture and integration blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://mike-gough.github.io'
google_analytics: 'UA-141675879-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:                'https://mike-gough.github.io/'
author:             'Mike Gough'
author_description: 'Integration Architect'

baseurl:            'https://mike-gough.github.io/'