name: Publish

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: setup-git-credentials
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        # git credentials use
        credentials: ${{secrets.GIT_CREDENTIALS}}

    # Runs commands
    - name: Clone Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make
        cd ..
        /usr/local/bin/publish deploy
